### ISSUE TITLE
pastuのx2の脱落

### ISSUE THREAD

**Issue by qq542vev** [skytomo221/tomon-zei-jbovlaste-bau-lo-ponbau#14]
こんにちは。何時もお世話になっています。

pastuのx2が抜けていることに気付いたので、ご連絡致しました。本家のjbovlaste <https://jbovlaste.lojban.org/dict/pastu>でも誤っているようです。こういった誤字脱字はIssueでご連絡しても問題なかったでしょうか。

**Comment by skytomo221** [comment]
ご指摘ありがとうございます。
たしかに`@2`が抜けていました。

> こういった誤字脱字はIssueでご連絡しても問題なかったでしょうか。

全然大丈夫です！
むしろ、誤字脱字やその他の問題もすべてIssueを通して連絡していただけると助かります。
そのほうが今ある問題点が把握しやすくなります。

- [Fix "pastu" wording](https://github.com/skytomo221/lojbantan-zei-jbovlaste/commit/613351e028b05012410ab78a220aed1581115e0f)
- [Fix typo](https://github.com/skytomo221/lojbantan-zei-jbovlaste/commit/a5e25a194df9dde5a419f72d2f84cb732eccf13f)

とりあえず、ここのコミットで修正しました。
問題がなければ、
この修正は、次のバージョン（Version 2.1）で反映されます。

よろしくお願いします。
